### ISSUE TITLE
Idle Timeout should be more obvious

### ISSUE THREAD

**Issue by isaacsanders** [elixir-plug/plug_cowboy#17]
I don't know if this library is the place to implement this, but shutdowns due to `idle_timeout` need to be made more obvious. I just lost over an hour of my time understanding that my application was silently failing because of this.

https://github.com/ninenines/cowboy/issues/1385

**Comment by josevalim** [comment]
Feel free to send a PR for clarification but overall I agree with Cowboy’s author. Pretty much everything in your stack (proxies, load balancer, etc) have idle timeouts and disconnecting when those happen is normal procedure. Thanks!
