### ISSUE TITLE
Telemetry event for `early_error`

### ISSUE THREAD

**Issue by binaryseed** [elixir-plug/plug_cowboy#33]
There are a category of requests that `cowboy` itself will respond to before it invokes the `Plug.Cowboy.Handler`, and thus they aren't detectable by any `telemetry` instrumentation currently in `plug` or `plug_cowboy`...

The `early_error` cowboy callback is implemented, and a subset of requests are logged: 

https://github.com/elixir-plug/plug_cowboy/blob/dc2972f926afd788e57f842d7da9f9171ca6e8f0/lib/plug/cowboy/stream.ex#L27-L31

It would be nice to emit a `telemetry` event for these requests so that they aren't lost. They consume real resources, but are currently invisible to any monitoring solution based on the exiting Plug events.

Thoughts @josevalim?

**Comment by josevalim** [comment]
What do you have in mind? A single event for early error?

**Comment by binaryseed** [comment]
Yes, we won’t get things like duration, but will be able to get minimal visibility into throughout with a single event.

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by binaryseed** [comment]
PR here: #34
