### ISSUE TITLE
How to use Drainer with phoenix

### ISSUE THREAD

**Issue by teamon** [elixir-plug/plug_cowboy#37]
It took me a while to figure out that in order to use `Plug.Cowboy.Drainer` with phoenix endpoint one must use it like this:

```elixir
# lib/myapp/application.ex
  def children do
    [
    # ...
      MyappWeb.Endpoint,
      {Plug.Cowboy.Drainer, refs: [MyappWeb.Endpoint.HTTP]},
    ]
  end
```

Would it make sense to mention this in README or Drainer docs?

**Comment by josevalim** [comment]
Phoenix adds the drainer by default. Please see the endpoint docs. :)

**Comment by teamon** [comment]
Ohhh, [since 1.5.0](https://github.com/phoenixframework/phoenix/blob/v1.5.3/CHANGELOG.md#150-2020-04-22).

Looks like the time to upgrade has come 😅 

Sorry for the noise and thank your for a blazing fast reply 🚅
