### ISSUE TITLE
Telemetry events based on cowboy_metrics_h

### ISSUE THREAD

**Issue by binaryseed** [elixir-plug/plug_cowboy#38]
Continuing discussion from https://github.com/phoenixframework/phoenix/pull/3869...

Current plug telemetry handlers for `:stop` and `:exception` are susceptible to being terminated _during_ their execution because the cowboy process can exit at any time after the request is complete.

This may be avoided by leveraging the built-in handler system of cowboy, especially `cowboy_metrics_h` which provides a way to execute a callback at the _end_ of each request with stats about its execution.

Wiring up the additional handler is trivial, the thing to figure out is what data from it to expose, and what to name the telemetry event...

https://ninenines.eu/docs/en/cowboy/2.8/manual/cowboy_metrics_h/

* Should we all the data directly or transform it so we aren't exposing raw cowboy data structures?

* Is `[:plug_cowboy, :metrics]` a reasonable name since it's providing summarized metrics (ie: not start and stop for spans)? Or `[:plug_cowboy, :terminate]` since it's called in the `terminate` phase of the cowboy process

**Comment by josevalim** [comment]
If we can't expose the current telemetry event as part of `cowboy_metrics_h`, then I don't think we should expose any event at all. It sounds counter intuitive for us to wrap `cowboy_metrics_h` with Telemetry. If you want cowboy metrics, then you should provide your own handler?

**Comment by josevalim** [comment]
Also, can we use `Plug.Cowboy.Stream` to emit `telemetry:span/3` events?

**Comment by binaryseed** [comment]
At the cowboy level, there's no notion of the `conn` so we can't replicate the existing events exactly...

It's true that a user could wire up their own cowboy stream handler config, but that's quite a step to require to get telemetry - I'd really love to get a good telemetry experience out of the box.

I thought about events inside `Plug.Cowboy.Stream` too and just took another look at that. I think that would be possible to provide an additional set of events:

* `[:plug_cowboy, :stream_handler, :start]` - this would happen in `init`
* `[:plug_cowboy, :stream_handler, :stop]` - this would happen in `info` when the `info` was a `:response` tuple

This would provide a span that'd represent the `cowboy` portion of the work pretty well. This could be used in addition to the existing `:plug_adapter` events of course. These appear to be reliable no matter what, even when there is an error raised in the request process

**Comment by josevalim** [comment]
Given that adding the other events did not work as we intended, my proposal is for you to give this a try using a custom handler (or custom metrics) before we standardize on it. Sure, writing a stream handler may not be straight-forward, but it doesn't mean we need to provide it as part of this lib. It can be defined externally and configured with an option.

I would like to avoid us adding a bunch of telemetry instrumentation and none of them work as expected.

I am considering "deprecating" the existing events, because I think they will catch a lot of people by surprise.

**Comment by binaryseed** [comment]
So if I can demonstrate that `:start` / `:stop` telemetry events inside `Plug.Cowboy.Stream` function as expected, you'd be open to considering including that?

I understand what you are saying about the existing events, I wasn't able to figure out what was going on, and I've heard a few other similar comments...

**Comment by josevalim** [comment]
Right. Things are backwards right now, we are adding the events, then we try them out in production, only to find out it was the wrong thing.

**Comment by binaryseed** [comment]
We're creating a new package to handle telemetry events through a Cowboy stream handler:

https://github.com/beam-telemetry/cowboy_telemetry
