### ISSUE TITLE
does not exist plug_cowboy package

### ISSUE THREAD

**Issue by kobatako** [elixir-plug/plug_cowboy#4]
I attempted to use master branch's plug and tried to install plug_cowboy.
However, I can not install it, and I get an error like the one below.

```
Failed to fetch record for 'hexpm/plug_cowboy' from registry (using cache)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name plug_cowboy (from: mix.exs) in registry
```

Have not you registered to hex yet? Or should I not use it yet?

**Comment by josevalim** [comment]
We will publish it soon. :) You can use plug_cowboy from git for now.

**Comment by kobatako** [comment]
Thank you for your reply.  plug_cowboy Installed via git, it worked.
I will try using.

**Comment by josevalim** [comment]
Released!
