### ISSUE TITLE
Adopt cowboy_telemetry

### ISSUE THREAD

**Issue by binaryseed** [elixir-plug/plug_cowboy#42]
We are creating a new Cowboy stream handler that will emit telemetry events:

* https://github.com/beam-telemetry/cowboy_telemetry

Once it's released, we should adopt it in `plug_cowboy` and include it by default, and also adopt it for the `early_error` logging.

**Comment by binaryseed** [comment]
This old PR demonstrates most of the necessary changes: https://github.com/elixir-plug/plug_cowboy/pull/39

**Comment by binaryseed** [comment]
PR opened: https://github.com/elixir-plug/plug_cowboy/pull/43

**Comment by josevalim** [comment]
Closing in favor of LR!
