### ISSUE TITLE
Using websockets

### ISSUE THREAD

**Issue by MrSoUndso** [elixir-plug/plug_cowboy#54]
Hi everybody, 
I hope this is not to offtopic, but is it possible to create websocket connections with plug_cowboy?

If yes, could you point my to any resources that show how to do it?

Thanks in advance

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

You should also be able to find some resources online or look at Phoenix for example. It basically resolves around passing your own dispatch rules to the underlying Cowboy server. Good luck!
