### ISSUE TITLE
Are there breaking changes between 1.0.0 and 2.0.0?

### ISSUE THREAD

**Issue by thbar** [elixir-plug/plug_cowboy#58]
I'm in the process of upgrading an app relying on `plug_cowboy` version `1.0.0`.

The changelog (https://github.com/elixir-plug/plug_cowboy/blob/master/CHANGELOG.md) does not mention anything related to `1.0.0`.

Are there breaking changes between `1.0.0` and the rest of the upgrades?

I have investigated and cannot see much changes (https://github.com/elixir-plug/plug_cowboy/compare/v1.0.0...v2.0.0) but would prefer to be sure!

Thank you (I can create a doc PR with my findings to help others).

**Comment by josevalim** [comment]
Yes, there are. v1 supports cowboy1 and v2 supports cowboy2 - so it is mostly the differences between Cowboy. If you are using Phoenix, this was handled transparently for you. :) We probably wouldn't merge a doc PR, as that is mostly in the past, but any information you can add here may be relevant! <3
