### ISSUE TITLE
v2.5.0 git tag missing

### ISSUE THREAD

**Issue by axelson** [elixir-plug/plug_cowboy#66]
The `v2.5.0` git tag is missing from this repository so the view source button on hexdocs (https://hexdocs.pm/plug_cowboy/Plug.Cowboy.html) gives a 404 (https://github.com/elixir-plug/plug_cowboy/blob/v2.5.0/lib/plug/cowboy.ex#L1)

**Comment by josevalim** [comment]
Fixed. I always tag but I always forget to push. :D

**Comment by axelson** [comment]
Yeah, it's really easy to do that :)
