### ISSUE TITLE
please make a new release to hex.pm to support otp24

### ISSUE THREAD

**Issue by enjolras1205** [elixir-plug/plug_cowboy#85]
cowboy version lower than 2.8.0 is using a deprecated_function erlang, get_stacktrace, making all error log to undef error:
Ranch protocol #PID<0.409.0> of listener Plug.Cowboy.TranslatorTest.HTTP (connection #PID<0.408.0>, stream id 1) terminated\n** (exit) :undef

error reproducing:
plug_cowboy: Release v2.5.2
erlang otp: 24
mix test test/plug/cowboy/translator_test.exs

**Comment by josevalim** [comment]
We support more recent Cowboy versions. You only need to do `mix deps.update cowboy`. :)
