### ISSUE TITLE
Update cowboy_telemetry requirement to v0.4.0

### ISSUE THREAD

**Issue by googol** [elixir-plug/plug_cowboy#86]
I'm currently trying to use the latest `opentelemetry_phoenix`, which depends on `telemetry ~> 1.0` via `opentelemetry_telemetry ~> 1.0`.

`plug_cowboy` is currently my blocker, since it depends on `cowboy_telemetry ~> 0.3`. `cowboy_telemetry` version 0.4.0 added support for `telemetry ~> 1.0`

**Comment by josevalim** [comment]
We depend on [cowboy_telemetry](https://hex.pm/packages/cowboy_telemetry) ~> 0.3, which means it accepts 0.4 as long as you call mix deps.update.

**Comment by googol** [comment]
Oh yeah that's true, tried it out in iex with `Version.match`

Sorry this was a bit of a nooby thing, I had to specify the new version `cowboy_telemetry` in my `mix.exs` to get the dependencies updated
