### ISSUE TITLE
Logging the conn logs sensitive information

### ISSUE THREAD

**Issue by jared-mackey** [elixir-plug/plug_cowboy#89]
Hi,

It looks like the exception logger from the plug here adds the entire `conn` to the logger metadata. The conn can contain sensitive information such as headers with authorization keys, cookies with sensitive values, or maybe even request/response bodies with sensitive data in them that should not be logged. In cases where `metadata: :all` is used this leads to those sensitive values being logged out which may be great for debugging, is not great for production environments where those values need to be scrubbed and or other serious implications. 

Should this be added to the metadata by default given the high sensitivity of those values and the somewhat common practice to allow all metadata?

Additionally, I do not see any mention of this in the docs for the plug. Maybe it's somewhere in the phoenix or plug docs though and I missed it.

Last but not least, thank you for the awesome project, we really appreciate all the hard work put into this community <3

**Comment by josevalim** [comment]
Hi @jared-mackey! How are you logging it? The default backend only logs metadata that can be converted to strings, which conn cannot.

**Comment by jared-mackey** [comment]
@josevalim Oh, that's a good bit of info to know. I am using the [logger_json](https://hexdocs.pm/logger_json/readme.html) library to log out all logs as json. Here's my config which is mostly taken from their documentation page linked there. They do mention that some parameters can be logged from plug/phoenix but I thought I had disabled them. 

```elixir
config :logger_json, :backend, metadata: :all, formatter: LoggerJSON.Formatters.DatadogLogger
config :logger, backends: [LoggerJSON]

filter_parameters = [
  ... all of my sensitive keys
]

config :phoenix, filter_parameters: filter_parameters
```

I had tested this a lot locally but I guess I didn't test an exception raising. :)

**Comment by josevalim** [comment]
Yeah, I think you will need a custom formatted because I am almost sure we added the conn for people to extract metadata.

we could also accept a config for removing it.

**Comment by josevalim** [comment]
A PR for the second one is welcome :)

**Comment by grzuy** [comment]
> @josevalim Oh, that's a good bit of info to know. I am using the [logger_json](https://hexdocs.pm/logger_json/readme.html) library to log out all logs as json. Here's my config which is mostly taken from their documentation page linked there. They do mention that some parameters can be logged from plug/phoenix but I thought I had disabled them.
> 
> ```elixir
> config :logger_json, :backend, metadata: :all, formatter: LoggerJSON.Formatters.DatadogLogger
> config :logger, backends: [LoggerJSON]
> 
> filter_parameters = [
>   ... all of my sensitive keys
> ]
> 
> config :phoenix, filter_parameters: filter_parameters
> ```
> 
> I had tested this a lot locally but I guess I didn't test an exception raising. :)

@jared-mackey For what is worth, I think you could consider also tuning `logger_json` configuration to `metadata: {:all_except, [:conn]}`.

I think if you turn off `conn` metadata on the `plug_cowboy` side you lose the ability of `logger_json` to extract and report useful request (not sensitive) information from the `conn` to report to Datadog, don't you?
