### ISSUE TITLE
Few changes from release v2.6.1 are not merged to master

### ISSUE THREAD

**Issue by akash-akya** [elixir-plug/plug_cowboy#93]
Looks like the release [v2.6.1](https://github.com/elixir-plug/plug_cowboy/releases/tag/v2.6.1) is cut on non main branch. The changelog at the master is still for `v2.6.0`. [Some code changes are missing as well](https://github.com/elixir-plug/plug_cowboy/compare/master...v2.6.1).

Latest hex package is `v2.6.1`: https://diff.hex.pm/diff/plug_cowboy/2.6.0..2.6.1.

**Comment by josevalim** [comment]
Thanks, fixed!
